# Generated by Django 2.0.4 on 2018-05-12 08:50

import breeds
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import sex
import size


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('sex', enumchoicefield.fields.EnumChoiceField(default=sex.Sex(1), enum_class=sex.Sex, max_length=6)),
                ('birth_year', models.PositiveIntegerField(default=2018)),
                ('breed', enumchoicefield.fields.EnumChoiceField(default=breeds.Breeds(12), enum_class=breeds.Breeds, max_length=19)),
                ('size', enumchoicefield.fields.EnumChoiceField(default=size.Size(1), enum_class=size.Size, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='DesiredMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', enumchoicefield.fields.EnumChoiceField(default=breeds.Breeds(12), enum_class=breeds.Breeds, max_length=19)),
                ('sex', enumchoicefield.fields.EnumChoiceField(default=sex.Sex(1), enum_class=sex.Sex, max_length=6)),
                ('size', enumchoicefield.fields.EnumChoiceField(default=size.Size(1), enum_class=size.Size, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_received', to='companions.Companion')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_sent', to='companions.Companion')),
            ],
        ),
        migrations.CreateModel(
            name='MatingSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_start', models.DateTimeField()),
                ('season_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_received', to='companions.Companion')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sent', to='companions.Companion')),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affinity_with_human', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('affinity_with_dog', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('shyness', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('activity', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('loudness', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('aggression', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('etc', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=15)),
                ('postal_code', models.PositiveIntegerField(default=0)),
                ('rough_address', models.CharField(max_length=100)),
                ('detailed_address', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=0)),
                ('gender', enumchoicefield.fields.EnumChoiceField(default=sex.Sex(1), enum_class=sex.Sex, max_length=6)),
                ('email', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted', models.BooleanField(default=False)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_received', to='companions.Companion')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_sent', to='companions.Companion')),
            ],
        ),
        migrations.AddField(
            model_name='companion',
            name='desired_mate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companions.DesiredMate'),
        ),
        migrations.AddField(
            model_name='companion',
            name='mating_season',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companions.MatingSeason'),
        ),
        migrations.AddField(
            model_name='companion',
            name='personality',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companions.Personality'),
        ),
        migrations.AddField(
            model_name='companion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companion', to=settings.AUTH_USER_MODEL),
        ),
    ]
