# Generated by Django 2.0.4 on 2018-05-03 12:11

import companions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', enumchoicefield.fields.EnumChoiceField(default=companions.models.Sex(1), enum_class=companions.models.Sex, max_length=6)),
                ('age', models.PositiveIntegerField(default=0)),
                ('breed', enumchoicefield.fields.EnumChoiceField(default=companions.models.Breeds(1), enum_class=companions.models.Breeds, max_length=7)),
                ('size', enumchoicefield.fields.EnumChoiceField(default=companions.models.Size(1), enum_class=companions.models.Size, max_length=6)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_companion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
